FROM node:12-stretch

USER node

RUN /home/node/src

WORKDIR /home/node/src

COPY --chown=node:node package-lock.json package.json ./

RUN npm ci

COPY  --chown=node:node . .

RUN npm ci

EXPOSE 3000 

CMD ["node", "index.js"]

//

FROM node:latest

RUN npm i -g nodemon

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install

COPY . /usr/src/app

EXPOSE 3000

CMD [ “nodemon”, “start” ]